export const CLASS_META={OFFICIAL:{label:"OFFICIAL",css:"official"},REPORTED:{label:"REPORTED",css:"reported"},FIELD_REPORT:{label:"FIELD REPORT",css:"field"},ESTIMATE:{label:"ESTIMATE",css:"estimate"},SIMULATION:{label:"SIMULATION",css:"simulation"},RECONSTRUCTED:{label:"RECONSTRUCTED",css:"reconstructed"}};

export const EVENTS=[
{id:"d0",nav:"DAY 0",date:"23 ก.ย.",time:"23 ก.ย. 2569",class:"OFFICIAL",title:"เริ่มมีคำเตือนฝนหนัก",summary:"กรมอุตุนิยมวิทยามีคำเตือนฝนหนักถึงหนักมากในภาคกลางและภาคตะวันออก รวมถึงกรุงเทพฯ และปริมณฑล ก่อนเหตุการณ์น้ำท่วมหนักฝั่งตะวันออกของกรุงเทพฯ",canal:"เฝ้าระวัง",rain:"ความเสี่ยงเพิ่ม",goal:"เตรียมของขึ้นที่สูง",source:"กรมอุตุนิยมวิทยา",url:"https://www5.tmd.go.th/warning-and-events/warning-storm/",water:.05,rainFx:.38,scene:"DAY 0 · ก่อนน้ำมา",sceneNote:"RECONSTRUCTED — แสดงลำดับเหตุการณ์ ไม่ใช่ระดับน้ำวัดจริง"},
{id:"d1",nav:"DAY 1",date:"25 ก.ย.",time:"25 ก.ย. 2569",class:"REPORTED",title:"ฝนสะสมหนัก ระบบระบายน้ำถูกกดดัน",summary:"รายงานเหตุการณ์ช่วงก่อนเช้ามืดวันที่ 26 แสดงว่าฝั่งตะวันออกของกรุงเทพฯ มีฝนสะสมหนัก น้ำบนถนนและคลองย่อยจำนวนมากเข้าสู่ระบบคลองหลัก",canal:"สูงขึ้น",rain:"หนักต่อเนื่อง",goal:"ย้ายของสำคัญ / เช็กไฟฟ้า",source:"Thai PBS",url:"https://www.thaipbs.th/news/content/558585",water:.20,rainFx:.92,scene:"DAY 1 · คลองรับน้ำ",sceneNote:"RECONSTRUCTED — ความสูงน้ำในฉากเป็น visualization"},
{id:"d2",nav:"03:00",date:"26 ก.ย.",time:"26 ก.ย. 2569 · 03:00 น.",class:"FIELD_REPORT",title:"ตื่นขึ้นมา — น้ำถึงครึ่งเตียง",summary:"ผู้ประสบเหตุในพื้นที่เล่าว่า ขณะนอนอยู่ชั้น 1 ตื่นประมาณ 03:00 น. พบว่าน้ำเข้าบ้านสูงถึงประมาณครึ่งเตียงและยังเพิ่มขึ้น ข้อมูลนี้เป็นพยานในพื้นที่ ไม่ใช่ค่าจากสถานีวัดทางการ",canal:"วิกฤตในพื้นที่",rain:"หนักข้ามคืน",goal:"ขึ้นที่สูง / รักษาการสื่อสาร",source:"Resident field report",url:"",water:.70,rainFx:1,scene:"03:00 · น้ำถึงครึ่งเตียง",sceneNote:"FIELD REPORT — ฉาก reconstructed จากคำบอกเล่า"},
{id:"d3",nav:"DAY 3",date:"27 ก.ย.",time:"27 ก.ย. 2569",class:"REPORTED",title:"ฝนเริ่มซา แต่น้ำในคลองยังสูง",summary:"รายงานสถานการณ์ระบุว่าหลังฝนเริ่มลด น้ำสะสมในคลองและพื้นที่ลุ่มยังสูง น้ำจากพื้นที่และคลองสาขายังต้องใช้เวลาระบายออก ทำให้ชุมชนไม่แห้งทันที",canal:"ยังสูง",rain:"เริ่มลด",goal:"วางแผนอยู่กับน้ำหลายวัน",source:"Thai PBS",url:"https://www.thaipbs.or.th/news/content/558666",water:.58,rainFx:.42,scene:"DAY 3 · ฝนซา แต่น้ำค้าง",sceneNote:"REPORTED + reconstructed visualization"},
{id:"d4",nav:"DAY 4",date:"28 ก.ย.",time:"28 ก.ย. 2569",class:"ESTIMATE",title:"คลองประเวศบุรีรมย์เป็นเส้นที่ระบายยาก",summary:"รายงานคำแถลงผู้ว่าฯ กทม. ระบุว่าคลองประเวศบุรีรมย์ระบายยากจากระยะทางและลักษณะคลอง และมีกรอบประเมินว่าการทยอยนำน้ำออกจากชุมชนอาจใช้เวลาราว 7 วัน กรอบนี้ไม่ใช่คำรับประกันสำหรับทุกบ้าน",canal:"สูง / ระบายช้า",rain:"ลดจากช่วงวิกฤต",goal:"บริหารน้ำ อาหาร ยา พลังงาน",source:"Thai PBS — รายงานคำแถลงผู้ว่าฯ กทม.",url:"https://www.thaipbs.or.th/news/content/558754",water:.46,rainFx:.24,scene:"DAY 4 · อยู่กับน้ำ",sceneNote:"ESTIMATE — ระยะเวลาจริงขึ้นกับฝนและระบบระบาย"},
{id:"now",nav:"NOW",date:"29 ก.ย.",time:"29 ก.ย. 2569 · Prototype snapshot",class:"FIELD_REPORT",title:"น้ำยังอยู่ แต่ชีวิตต้องเดินต่อ",summary:"FIELD REPORT ระบุว่าน้ำในบ้านยังประมาณระดับเข่า และรอบบ้านบางจุดระดับเอว–อก ขณะที่รายงานสาธารณะชี้ว่าถนนหลักบางส่วนเริ่มฟื้น แต่ชุมชนลุ่มต่ำต้องใช้เวลาระบายต่อ เป้าหมายของเกมจึงเปลี่ยนจากเอาตัวรอดฉุกเฉินเป็นการจัดชีวิตให้ปลอดภัยทีละวัน",canal:"ยังมีน้ำมาก",rain:"เบากว่าช่วงวิกฤต",goal:"รักษาความปลอดภัยและความต่อเนื่อง",source:"FIELD REPORT + public situation report",url:"https://thestandard.co/chatchart-bangkok-flood-dry-latkrabang/",water:.33,rainFx:.14,scene:"NOW · ชีวิตยังเดินต่อ",sceneNote:"FIELD REPORT + reconstructed visualization"}];

export const MISSIONS=[
["electric","แยกพื้นที่ไฟฟ้าออกจากน้ำ","อย่าสัมผัสปลั๊ก สายไฟ หรืออุปกรณ์ที่โดนน้ำหากยังไม่แน่ใจว่าปลอดภัย"],
["essentials","ย้ายยา เอกสาร โทรศัพท์ และน้ำดื่มขึ้นที่สูง","เก็บของจำเป็นต่อสุขภาพและการสื่อสารไว้ในจุดแห้งที่หยิบได้ง่าย"],
["contact","กำหนดเวลาติดต่อคนในบ้านหรือเพื่อนบ้าน","ช่วยให้รู้เร็วหากมีใครขาดการติดต่อหรือเริ่มต้องการความช่วยเหลือ"],
["route","ทำทางขึ้นพื้นที่สูงให้โล่ง","สำคัญเป็นพิเศษในบ้านที่มีเด็ก ผู้สูงอายุ ผู้ป่วย หรือสัตว์เลี้ยง"],
["log","บันทึกระดับน้ำจากจุดอ้างอิงเดิม","ใช้จุดและเวลาเดิมเพื่อติดตามแนวโน้มขึ้น คงที่ หรือลด"],
["trigger","รู้ Trigger ที่ต้องขอความช่วยเหลือ","น้ำขึ้นเร็วผิดปกติ ไฟฟ้ารั่ว คนป่วยฉุกเฉิน หรือทางขึ้นที่สูงไม่ปลอดภัย = ขอความช่วยเหลือ"]].map(([id,title,detail])=>({id,title,detail}));

export const SOURCES=[
{type:"OFFICIAL",title:"กรมอุตุนิยมวิทยา — คำเตือนสภาพอากาศ",note:"ฐานข้อมูลก่อนช่วงฝนหนัก",url:"https://www5.tmd.go.th/warning-and-events/warning-storm/"},
{type:"REPORTED",title:"Thai PBS — ฝนซาแต่น้ำคลองยังสูง",note:"ประกอบภาพสถานการณ์หลังฝนลด",url:"https://www.thaipbs.or.th/news/content/558666"},
{type:"ESTIMATE",title:"Thai PBS — รายงานกรอบระบายน้ำคลองประเวศฯ ราว 7 วัน",note:"ต้องแสดงเป็น Estimate ไม่ใช่เวลารับประกัน",url:"https://www.thaipbs.or.th/news/content/558754"},
{type:"FIELD_REPORT",title:"Resident report — 26 ก.ย. 03:00 น้ำถึงครึ่งเตียง",note:"พยานในพื้นที่ แยกจากค่าทางการ",url:""},
{type:"OFFICIAL",title:"MEA — ความปลอดภัยไฟฟ้าช่วงฝน/น้ำท่วม",note:"ฐานคำแนะนำด้านไฟฟ้า",url:"https://www.mea.or.th/public-relations/corporate-news-activities/announcement/mea-ddpm-rainy-safety-5tips"}];